spring:
  redis: #以下redis部分自行修改
    host: 192.168.5.231
    port: 6379
    #       password: dh35hebsd87ed9df9d0kemd9
    lettuce:
      pool:
        min-idle: 4
        max-active: 8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 10Mb
  remote:
    rpc:
      zookeeper: 192.168.5.231:2181